### ISSUE TITLE
회원 로그인

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#29]
### TODO
회원 로그인 API
요청 URL : POST /user-service/login
요청 파라미터

email : 이메일
password : 비밀번호

---

### 로그인 처리를 위한 UsernamePasswordAuthenticationFilter 구현
- 인증 처리 : attemptAuthentication()
- 인증 성공 처리 : AbstractAuthenticationProcessingFilter.successfulAuthentication()

Step01(인증객체 수신 및 변환) : Post 로그인 요청 객체를 stream으로 읽어 spring-security에서 인식할 수 있는 인증 객체(UsernamePassworedAuthenticationToken)로 변환

Step02(인증처리를 위한 객체 저장) : 인증객체를 처리할 수 있는 Authentication Manager 에 인증 객체 저장

Step03 : 사용자 요청 시 인증을 처리하는 AuthenticationFilter를 spring-security에 등록

Step04 : 인증 관련 설정을 기술하는 configure(AuthenticationManagerBuilder) 구현
 - 로그인 처리를 진행하는 관련 Bean들을 이용한 configure 기술

Step05 : spring-security의 인증을 처리하는 UserDetailsService를 이용한 로그인 처리(사용자 로그인 요청 정보 인증 처리)

Step06 : 인증 완료 후 AuthenticationFilter의 successfulAuthentication에서 JWT 발급

---

POST /user-service/login
Flow01 : UsernamePasswordAuthenticationFilter.attemptAuthentication : Authentication
Flow02 : UserDetailsService.loadUserByUsername : User
Flow03 : UsernamePasswordAuthenticationFilter.successfulAuthentication

### Reference URL : [docs.spring.io:UsernamePasswordAuthenticationFilter](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.html)

**Comment by choi-ys** [comment]
### 회원 로그인 api
요청 URL : POST /user-service/login
요청 파라미터
- email : 이메일
- password : 비밀번호
