### ISSUE TITLE
Grapana prometheus datasource url 설정 오류 대응

### ISSUE THREAD

**Issue by re-mora** [choi-ys/msa-with-spring-cloud#69]
![image](https://user-images.githubusercontent.com/14158670/149874213-d1c6e6c1-6e00-48dc-8a3e-b7ba9dc3361a.png)

오류 내용 : Error reading Prometheus: Post "http://localhost:9090/api/v1/query": dial tcp 127.0.0.1:9090: connect: connection refused

해결 : Prometheus server url 수정
 - AS-IS : http://localhost:9090/
 - TO-BE : http://192.168.1.57:9090/

![image](https://user-images.githubusercontent.com/14158670/149874285-c31f64d9-24f2-409f-8e7b-83a9d78d6d1e.png)

---

### Rererence URL
[Grapana community issue](https://community.grafana.com/t/alert-issue-in-dashboard-with-prometheus-dashboard-request-handler-error-post-http-localhost-9090-api-v1-query-range-dial-tcp-1-connect-connection-refused/50756)

**Comment by choi-ys** [comment]
### Rererence URL
[Grapana official](https://community.grafana.com/t/alert-issue-in-dashboard-with-prometheus-dashboard-request-handler-error-post-http-localhost-9090-api-v1-query-range-dial-tcp-1-connect-connection-refused/50756)
